export const ZERO_ADDRESS = "0x0000000000000000000000000000000000000000";
export const POKEMON_URLS = [
  { name: "bulbasaur", url: "https://pokeapi.co/api/v2/pokemon/1/" },
  { name: "ivysaur", url: "https://pokeapi.co/api/v2/pokemon/2/" },
  { name: "venusaur", url: "https://pokeapi.co/api/v2/pokemon/3/" },
  { name: "charmander", url: "https://pokeapi.co/api/v2/pokemon/4/" },
  { name: "charmeleon", url: "https://pokeapi.co/api/v2/pokemon/5/" },
  { name: "charizard", url: "https://pokeapi.co/api/v2/pokemon/6/" },
  { name: "squirtle", url: "https://pokeapi.co/api/v2/pokemon/7/" },
  { name: "wartortle", url: "https://pokeapi.co/api/v2/pokemon/8/" },
  { name: "blastoise", url: "https://pokeapi.co/api/v2/pokemon/9/" },
  { name: "caterpie", url: "https://pokeapi.co/api/v2/pokemon/10/" },
  { name: "metapod", url: "https://pokeapi.co/api/v2/pokemon/11/" },
  { name: "butterfree", url: "https://pokeapi.co/api/v2/pokemon/12/" },
  { name: "weedle", url: "https://pokeapi.co/api/v2/pokemon/13/" },
  { name: "kakuna", url: "https://pokeapi.co/api/v2/pokemon/14/" },
  { name: "beedrill", url: "https://pokeapi.co/api/v2/pokemon/15/" },
  { name: "pidgey", url: "https://pokeapi.co/api/v2/pokemon/16/" },
  { name: "pidgeotto", url: "https://pokeapi.co/api/v2/pokemon/17/" },
  { name: "pidgeot", url: "https://pokeapi.co/api/v2/pokemon/18/" },
  { name: "rattata", url: "https://pokeapi.co/api/v2/pokemon/19/" },
  { name: "raticate", url: "https://pokeapi.co/api/v2/pokemon/20/" },
  { name: "spearow", url: "https://pokeapi.co/api/v2/pokemon/21/" },
  { name: "fearow", url: "https://pokeapi.co/api/v2/pokemon/22/" },
  { name: "ekans", url: "https://pokeapi.co/api/v2/pokemon/23/" },
  { name: "arbok", url: "https://pokeapi.co/api/v2/pokemon/24/" },
  { name: "pikachu", url: "https://pokeapi.co/api/v2/pokemon/25/" },
  { name: "raichu", url: "https://pokeapi.co/api/v2/pokemon/26/" },
  { name: "sandshrew", url: "https://pokeapi.co/api/v2/pokemon/27/" },
  { name: "sandslash", url: "https://pokeapi.co/api/v2/pokemon/28/" },
  { name: "nidoran-f", url: "https://pokeapi.co/api/v2/pokemon/29/" },
  { name: "nidorina", url: "https://pokeapi.co/api/v2/pokemon/30/" },
  { name: "nidoqueen", url: "https://pokeapi.co/api/v2/pokemon/31/" },
  { name: "nidoran-m", url: "https://pokeapi.co/api/v2/pokemon/32/" },
  { name: "nidorino", url: "https://pokeapi.co/api/v2/pokemon/33/" },
  { name: "nidoking", url: "https://pokeapi.co/api/v2/pokemon/34/" },
  { name: "clefairy", url: "https://pokeapi.co/api/v2/pokemon/35/" },
  { name: "clefable", url: "https://pokeapi.co/api/v2/pokemon/36/" },
  { name: "vulpix", url: "https://pokeapi.co/api/v2/pokemon/37/" },
  { name: "ninetales", url: "https://pokeapi.co/api/v2/pokemon/38/" },
  { name: "jigglypuff", url: "https://pokeapi.co/api/v2/pokemon/39/" },
  { name: "wigglytuff", url: "https://pokeapi.co/api/v2/pokemon/40/" },
  { name: "zubat", url: "https://pokeapi.co/api/v2/pokemon/41/" },
  { name: "golbat", url: "https://pokeapi.co/api/v2/pokemon/42/" },
  { name: "oddish", url: "https://pokeapi.co/api/v2/pokemon/43/" },
  { name: "gloom", url: "https://pokeapi.co/api/v2/pokemon/44/" },
  { name: "vileplume", url: "https://pokeapi.co/api/v2/pokemon/45/" },
  { name: "paras", url: "https://pokeapi.co/api/v2/pokemon/46/" },
  { name: "parasect", url: "https://pokeapi.co/api/v2/pokemon/47/" },
  { name: "venonat", url: "https://pokeapi.co/api/v2/pokemon/48/" },
  { name: "venomoth", url: "https://pokeapi.co/api/v2/pokemon/49/" },
  { name: "diglett", url: "https://pokeapi.co/api/v2/pokemon/50/" },
  { name: "dugtrio", url: "https://pokeapi.co/api/v2/pokemon/51/" },
  { name: "meowth", url: "https://pokeapi.co/api/v2/pokemon/52/" },
  { name: "persian", url: "https://pokeapi.co/api/v2/pokemon/53/" },
  { name: "psyduck", url: "https://pokeapi.co/api/v2/pokemon/54/" },
  { name: "golduck", url: "https://pokeapi.co/api/v2/pokemon/55/" },
  { name: "mankey", url: "https://pokeapi.co/api/v2/pokemon/56/" },
  { name: "primeape", url: "https://pokeapi.co/api/v2/pokemon/57/" },
  { name: "growlithe", url: "https://pokeapi.co/api/v2/pokemon/58/" },
  { name: "arcanine", url: "https://pokeapi.co/api/v2/pokemon/59/" },
  { name: "poliwag", url: "https://pokeapi.co/api/v2/pokemon/60/" },
  { name: "poliwhirl", url: "https://pokeapi.co/api/v2/pokemon/61/" },
  { name: "poliwrath", url: "https://pokeapi.co/api/v2/pokemon/62/" },
  { name: "abra", url: "https://pokeapi.co/api/v2/pokemon/63/" },
  { name: "kadabra", url: "https://pokeapi.co/api/v2/pokemon/64/" },
  { name: "alakazam", url: "https://pokeapi.co/api/v2/pokemon/65/" },
  { name: "machop", url: "https://pokeapi.co/api/v2/pokemon/66/" },
  { name: "machoke", url: "https://pokeapi.co/api/v2/pokemon/67/" },
  { name: "machamp", url: "https://pokeapi.co/api/v2/pokemon/68/" },
  { name: "bellsprout", url: "https://pokeapi.co/api/v2/pokemon/69/" },
  { name: "weepinbell", url: "https://pokeapi.co/api/v2/pokemon/70/" },
  { name: "victreebel", url: "https://pokeapi.co/api/v2/pokemon/71/" },
  { name: "tentacool", url: "https://pokeapi.co/api/v2/pokemon/72/" },
  { name: "tentacruel", url: "https://pokeapi.co/api/v2/pokemon/73/" },
  { name: "geodude", url: "https://pokeapi.co/api/v2/pokemon/74/" },
  { name: "graveler", url: "https://pokeapi.co/api/v2/pokemon/75/" },
  { name: "golem", url: "https://pokeapi.co/api/v2/pokemon/76/" },
  { name: "ponyta", url: "https://pokeapi.co/api/v2/pokemon/77/" },
  { name: "rapidash", url: "https://pokeapi.co/api/v2/pokemon/78/" },
  { name: "slowpoke", url: "https://pokeapi.co/api/v2/pokemon/79/" },
  { name: "slowbro", url: "https://pokeapi.co/api/v2/pokemon/80/" },
  { name: "magnemite", url: "https://pokeapi.co/api/v2/pokemon/81/" },
  { name: "magneton", url: "https://pokeapi.co/api/v2/pokemon/82/" },
  { name: "farfetchd", url: "https://pokeapi.co/api/v2/pokemon/83/" },
  { name: "doduo", url: "https://pokeapi.co/api/v2/pokemon/84/" },
  { name: "dodrio", url: "https://pokeapi.co/api/v2/pokemon/85/" },
  { name: "seel", url: "https://pokeapi.co/api/v2/pokemon/86/" },
  { name: "dewgong", url: "https://pokeapi.co/api/v2/pokemon/87/" },
  { name: "grimer", url: "https://pokeapi.co/api/v2/pokemon/88/" },
  { name: "muk", url: "https://pokeapi.co/api/v2/pokemon/89/" },
  { name: "shellder", url: "https://pokeapi.co/api/v2/pokemon/90/" },
  { name: "cloyster", url: "https://pokeapi.co/api/v2/pokemon/91/" },
  { name: "gastly", url: "https://pokeapi.co/api/v2/pokemon/92/" },
  { name: "haunter", url: "https://pokeapi.co/api/v2/pokemon/93/" },
  { name: "gengar", url: "https://pokeapi.co/api/v2/pokemon/94/" },
  { name: "onix", url: "https://pokeapi.co/api/v2/pokemon/95/" },
  { name: "drowzee", url: "https://pokeapi.co/api/v2/pokemon/96/" },
  { name: "hypno", url: "https://pokeapi.co/api/v2/pokemon/97/" },
  { name: "krabby", url: "https://pokeapi.co/api/v2/pokemon/98/" },
  { name: "kingler", url: "https://pokeapi.co/api/v2/pokemon/99/" },
  { name: "voltorb", url: "https://pokeapi.co/api/v2/pokemon/100/" },
  { name: "electrode", url: "https://pokeapi.co/api/v2/pokemon/101/" },
  { name: "exeggcute", url: "https://pokeapi.co/api/v2/pokemon/102/" },
  { name: "exeggutor", url: "https://pokeapi.co/api/v2/pokemon/103/" },
  { name: "cubone", url: "https://pokeapi.co/api/v2/pokemon/104/" },
  { name: "marowak", url: "https://pokeapi.co/api/v2/pokemon/105/" },
  { name: "hitmonlee", url: "https://pokeapi.co/api/v2/pokemon/106/" },
  { name: "hitmonchan", url: "https://pokeapi.co/api/v2/pokemon/107/" },
  { name: "lickitung", url: "https://pokeapi.co/api/v2/pokemon/108/" },
  { name: "koffing", url: "https://pokeapi.co/api/v2/pokemon/109/" },
  { name: "weezing", url: "https://pokeapi.co/api/v2/pokemon/110/" },
  { name: "rhyhorn", url: "https://pokeapi.co/api/v2/pokemon/111/" },
  { name: "rhydon", url: "https://pokeapi.co/api/v2/pokemon/112/" },
  { name: "chansey", url: "https://pokeapi.co/api/v2/pokemon/113/" },
  { name: "tangela", url: "https://pokeapi.co/api/v2/pokemon/114/" },
  { name: "kangaskhan", url: "https://pokeapi.co/api/v2/pokemon/115/" },
  { name: "horsea", url: "https://pokeapi.co/api/v2/pokemon/116/" },
  { name: "seadra", url: "https://pokeapi.co/api/v2/pokemon/117/" },
  { name: "goldeen", url: "https://pokeapi.co/api/v2/pokemon/118/" },
  { name: "seaking", url: "https://pokeapi.co/api/v2/pokemon/119/" },
  { name: "staryu", url: "https://pokeapi.co/api/v2/pokemon/120/" },
  { name: "starmie", url: "https://pokeapi.co/api/v2/pokemon/121/" },
  { name: "mr-mime", url: "https://pokeapi.co/api/v2/pokemon/122/" },
  { name: "scyther", url: "https://pokeapi.co/api/v2/pokemon/123/" },
  { name: "jynx", url: "https://pokeapi.co/api/v2/pokemon/124/" },
  { name: "electabuzz", url: "https://pokeapi.co/api/v2/pokemon/125/" },
  { name: "magmar", url: "https://pokeapi.co/api/v2/pokemon/126/" },
  { name: "pinsir", url: "https://pokeapi.co/api/v2/pokemon/127/" },
  { name: "tauros", url: "https://pokeapi.co/api/v2/pokemon/128/" },
  { name: "magikarp", url: "https://pokeapi.co/api/v2/pokemon/129/" },
  { name: "gyarados", url: "https://pokeapi.co/api/v2/pokemon/130/" },
  { name: "lapras", url: "https://pokeapi.co/api/v2/pokemon/131/" },
  { name: "ditto", url: "https://pokeapi.co/api/v2/pokemon/132/" },
  { name: "eevee", url: "https://pokeapi.co/api/v2/pokemon/133/" },
  { name: "vaporeon", url: "https://pokeapi.co/api/v2/pokemon/134/" },
  { name: "jolteon", url: "https://pokeapi.co/api/v2/pokemon/135/" },
  { name: "flareon", url: "https://pokeapi.co/api/v2/pokemon/136/" },
  { name: "porygon", url: "https://pokeapi.co/api/v2/pokemon/137/" },
  { name: "omanyte", url: "https://pokeapi.co/api/v2/pokemon/138/" },
  { name: "omastar", url: "https://pokeapi.co/api/v2/pokemon/139/" },
  { name: "kabuto", url: "https://pokeapi.co/api/v2/pokemon/140/" },
  { name: "kabutops", url: "https://pokeapi.co/api/v2/pokemon/141/" },
  { name: "aerodactyl", url: "https://pokeapi.co/api/v2/pokemon/142/" },
  { name: "snorlax", url: "https://pokeapi.co/api/v2/pokemon/143/" },
  { name: "articuno", url: "https://pokeapi.co/api/v2/pokemon/144/" },
  { name: "zapdos", url: "https://pokeapi.co/api/v2/pokemon/145/" },
  { name: "moltres", url: "https://pokeapi.co/api/v2/pokemon/146/" },
  { name: "dratini", url: "https://pokeapi.co/api/v2/pokemon/147/" },
  { name: "dragonair", url: "https://pokeapi.co/api/v2/pokemon/148/" },
  { name: "dragonite", url: "https://pokeapi.co/api/v2/pokemon/149/" },
  { name: "mewtwo", url: "https://pokeapi.co/api/v2/pokemon/150/" },
  { name: "mew", url: "https://pokeapi.co/api/v2/pokemon/151/" },
];

export const POKEMON_DETAILS = [
  {
    name: "bulbasaur",
    id: 1,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/1.png",
  },
  {
    name: "ivysaur",
    id: 2,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/2.png",
  },
  {
    name: "venusaur",
    id: 3,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/3.png",
  },
  {
    name: "charmander",
    id: 4,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/4.png",
  },
  {
    name: "charmeleon",
    id: 5,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/5.png",
  },
  {
    name: "caterpie",
    id: 10,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10.png",
  },
  {
    name: "charizard",
    id: 6,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/6.png",
  },
  {
    name: "wartortle",
    id: 8,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/8.png",
  },
  {
    name: "metapod",
    id: 11,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/11.png",
  },
  {
    name: "squirtle",
    id: 7,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/7.png",
  },
  {
    name: "blastoise",
    id: 9,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/9.png",
  },
  {
    name: "butterfree",
    id: 12,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/12.png",
  },
  {
    name: "weedle",
    id: 13,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/13.png",
  },
  {
    name: "beedrill",
    id: 15,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/15.png",
  },
  {
    name: "kakuna",
    id: 14,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/14.png",
  },
  {
    name: "pidgey",
    id: 16,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/16.png",
  },
  {
    name: "pidgeotto",
    id: 17,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/17.png",
  },
  {
    name: "pidgeot",
    id: 18,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/18.png",
  },
  {
    name: "rattata",
    id: 19,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/19.png",
  },
  {
    name: "spearow",
    id: 21,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/21.png",
  },
  {
    name: "raticate",
    id: 20,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/20.png",
  },
  {
    name: "fearow",
    id: 22,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/22.png",
  },
  {
    name: "ekans",
    id: 23,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/23.png",
  },
  {
    name: "arbok",
    id: 24,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/24.png",
  },
  {
    name: "pikachu",
    id: 25,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/25.png",
  },
  {
    name: "raichu",
    id: 26,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/26.png",
  },
  {
    name: "sandshrew",
    id: 27,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/27.png",
  },
  {
    name: "sandslash",
    id: 28,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/28.png",
  },
  {
    name: "nidoran-f",
    id: 29,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/29.png",
  },
  {
    name: "nidorina",
    id: 30,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/30.png",
  },
  {
    name: "nidoqueen",
    id: 31,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/31.png",
  },
  {
    name: "nidoran-m",
    id: 32,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/32.png",
  },
  {
    name: "nidorino",
    id: 33,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/33.png",
  },
  {
    name: "nidoking",
    id: 34,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/34.png",
  },
  {
    name: "clefairy",
    id: 35,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/35.png",
  },
  {
    name: "clefable",
    id: 36,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/36.png",
  },
  {
    name: "vulpix",
    id: 37,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/37.png",
  },
  {
    name: "ninetales",
    id: 38,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/38.png",
  },
  {
    name: "jigglypuff",
    id: 39,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/39.png",
  },
  {
    name: "wigglytuff",
    id: 40,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/40.png",
  },
  {
    name: "zubat",
    id: 41,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/41.png",
  },
  {
    name: "golbat",
    id: 42,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/42.png",
  },
  {
    name: "oddish",
    id: 43,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/43.png",
  },
  {
    name: "gloom",
    id: 44,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/44.png",
  },
  {
    name: "vileplume",
    id: 45,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/45.png",
  },
  {
    name: "paras",
    id: 46,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/46.png",
  },
  {
    name: "parasect",
    id: 47,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/47.png",
  },
  {
    name: "venonat",
    id: 48,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/48.png",
  },
  {
    name: "arcanine",
    id: 59,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/59.png",
  },
  {
    name: "venomoth",
    id: 49,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/49.png",
  },
  {
    name: "diglett",
    id: 50,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/50.png",
  },
  {
    name: "dugtrio",
    id: 51,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/51.png",
  },
  {
    name: "meowth",
    id: 52,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/52.png",
  },
  {
    name: "persian",
    id: 53,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/53.png",
  },
  {
    name: "psyduck",
    id: 54,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/54.png",
  },
  {
    name: "golduck",
    id: 55,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/55.png",
  },
  {
    name: "primeape",
    id: 57,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/57.png",
  },
  {
    name: "growlithe",
    id: 58,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/58.png",
  },
  {
    name: "poliwag",
    id: 60,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/60.png",
  },
  {
    name: "poliwhirl",
    id: 61,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/61.png",
  },
  {
    name: "poliwrath",
    id: 62,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/62.png",
  },
  {
    name: "mankey",
    id: 56,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/56.png",
  },
  {
    name: "abra",
    id: 63,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/63.png",
  },
  {
    name: "kadabra",
    id: 64,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/64.png",
  },
  {
    name: "alakazam",
    id: 65,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/65.png",
  },
  {
    name: "machop",
    id: 66,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/66.png",
  },
  {
    name: "machoke",
    id: 67,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/67.png",
  },
  {
    name: "machamp",
    id: 68,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/68.png",
  },
  {
    name: "bellsprout",
    id: 69,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/69.png",
  },
  {
    name: "weepinbell",
    id: 70,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/70.png",
  },
  {
    name: "victreebel",
    id: 71,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/71.png",
  },
  {
    name: "tentacool",
    id: 72,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/72.png",
  },
  {
    name: "tentacruel",
    id: 73,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/73.png",
  },
  {
    name: "geodude",
    id: 74,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/74.png",
  },
  {
    name: "graveler",
    id: 75,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/75.png",
  },
  {
    name: "golem",
    id: 76,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/76.png",
  },
  {
    name: "ponyta",
    id: 77,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/77.png",
  },
  {
    name: "rapidash",
    id: 78,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/78.png",
  },
  {
    name: "slowpoke",
    id: 79,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/79.png",
  },
  {
    name: "slowbro",
    id: 80,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/80.png",
  },
  {
    name: "magnemite",
    id: 81,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/81.png",
  },
  {
    name: "magneton",
    id: 82,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/82.png",
  },
  {
    name: "farfetchd",
    id: 83,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/83.png",
  },
  {
    name: "doduo",
    id: 84,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/84.png",
  },
  {
    name: "dodrio",
    id: 85,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/85.png",
  },
  {
    name: "seel",
    id: 86,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/86.png",
  },
  {
    name: "dewgong",
    id: 87,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/87.png",
  },
  {
    name: "grimer",
    id: 88,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/88.png",
  },
  {
    name: "muk",
    id: 89,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/89.png",
  },
  {
    name: "shellder",
    id: 90,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/90.png",
  },
  {
    name: "cloyster",
    id: 91,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/91.png",
  },
  {
    name: "gastly",
    id: 92,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/92.png",
  },
  {
    name: "haunter",
    id: 93,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/93.png",
  },
  {
    name: "gengar",
    id: 94,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/94.png",
  },
  {
    name: "onix",
    id: 95,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/95.png",
  },
  {
    name: "drowzee",
    id: 96,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/96.png",
  },
  {
    name: "hypno",
    id: 97,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/97.png",
  },
  {
    name: "krabby",
    id: 98,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/98.png",
  },
  {
    name: "kingler",
    id: 99,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/99.png",
  },
  {
    name: "voltorb",
    id: 100,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/100.png",
  },
  {
    name: "electrode",
    id: 101,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/101.png",
  },
  {
    name: "exeggcute",
    id: 102,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/102.png",
  },
  {
    name: "exeggutor",
    id: 103,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/103.png",
  },
  {
    name: "cubone",
    id: 104,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/104.png",
  },
  {
    name: "marowak",
    id: 105,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/105.png",
  },
  {
    name: "hitmonlee",
    id: 106,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/106.png",
  },
  {
    name: "hitmonchan",
    id: 107,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/107.png",
  },
  {
    name: "lickitung",
    id: 108,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/108.png",
  },
  {
    name: "koffing",
    id: 109,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/109.png",
  },
  {
    name: "weezing",
    id: 110,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/110.png",
  },
  {
    name: "rhyhorn",
    id: 111,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/111.png",
  },
  {
    name: "rhydon",
    id: 112,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/112.png",
  },
  {
    name: "chansey",
    id: 113,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/113.png",
  },
  {
    name: "tangela",
    id: 114,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/114.png",
  },
  {
    name: "kangaskhan",
    id: 115,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/115.png",
  },
  {
    name: "horsea",
    id: 116,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/116.png",
  },
  {
    name: "seadra",
    id: 117,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/117.png",
  },
  {
    name: "goldeen",
    id: 118,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/118.png",
  },
  {
    name: "seaking",
    id: 119,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/119.png",
  },
  {
    name: "staryu",
    id: 120,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/120.png",
  },
  {
    name: "starmie",
    id: 121,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/121.png",
  },
  {
    name: "mr-mime",
    id: 122,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/122.png",
  },
  {
    name: "scyther",
    id: 123,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/123.png",
  },
  {
    name: "jynx",
    id: 124,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/124.png",
  },
  {
    name: "electabuzz",
    id: 125,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/125.png",
  },
  {
    name: "magmar",
    id: 126,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/126.png",
  },
  {
    name: "pinsir",
    id: 127,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/127.png",
  },
  {
    name: "tauros",
    id: 128,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/128.png",
  },
  {
    name: "magikarp",
    id: 129,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/129.png",
  },
  {
    name: "gyarados",
    id: 130,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/130.png",
  },
  {
    name: "lapras",
    id: 131,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/131.png",
  },
  {
    name: "ditto",
    id: 132,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/132.png",
  },
  {
    name: "eevee",
    id: 133,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/133.png",
  },
  {
    name: "vaporeon",
    id: 134,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/134.png",
  },
  {
    name: "jolteon",
    id: 135,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/135.png",
  },
  {
    name: "flareon",
    id: 136,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/136.png",
  },
  {
    name: "porygon",
    id: 137,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/137.png",
  },
  {
    name: "omanyte",
    id: 138,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/138.png",
  },
  {
    name: "omastar",
    id: 139,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/139.png",
  },
  {
    name: "kabuto",
    id: 140,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/140.png",
  },
  {
    name: "kabutops",
    id: 141,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/141.png",
  },
  {
    name: "aerodactyl",
    id: 142,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/142.png",
  },
  {
    name: "snorlax",
    id: 143,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/143.png",
  },
  {
    name: "articuno",
    id: 144,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/144.png",
  },
  {
    name: "zapdos",
    id: 145,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/145.png",
  },
  {
    name: "moltres",
    id: 146,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/146.png",
  },
  {
    name: "dratini",
    id: 147,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/147.png",
  },
  {
    name: "dragonair",
    id: 148,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/148.png",
  },
  {
    name: "dragonite",
    id: 149,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/149.png",
  },
  {
    name: "mewtwo",
    id: 150,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/150.png",
  },
  {
    name: "mew",
    id: 151,
    img: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/151.png",
  },
];
